logging:
  level:
    root: ERROR

server:
  port: 8088

spring:
  datasource:
    #name : basic
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      name: primary
      url: jdbc:mysql://localhost:3306/xdmy?useSSL=false&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    secondary:
      name: secondary
      url: jdbc:mysql://localhost:3306/temp?useSSL=false&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    druid:
      filters: stat
      driver-class--name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  mvc:
    view:
      prefix: /
      suffix: .jsp
    thymeleaf:
      cache: false
      enabled: false
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB